<?php

namespace Ayigi\PlateFormeBundle\Repository;

/**
 * PaysDestinationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaysDestinationRepository extends \Doctrine\ORM\EntityRepository
{
}
