<?php

namespace Ayigi\PlateFormeBundle\Repository;

/**
 * TarifServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
