# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Ayigi\PlateFormeBundle\Entity\Administrateur: sha512
        Ayigi\ClientBundle\Entity\Client: sha512

    role_hierarchy:
        ROLE_CLIENT: ROLE_USER
        ROLE_ADMIN: [ROLE_ADMIN, ROLE_SUPERVISEUR, ROLE_SERVICECLIENT]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    
    providers:
        main:
            entity: { class: Ayigi\PlateFormeBundle\Entity\Administrateur, property: username }
        
        client:
            entity: { class: Ayigi\ClientBundle\Entity\Client, property: username }

        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        ayigi_login:
            pattern: ^/login$
            anonymous: true

        plateforme_admin:
            pattern:    ^/ayigi-admin/
            anonymous:  false
            provider:  main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   logout
                target: /
        
        client_ayigi_login:
            pattern: ^/login-client$
            anonymous: true

        plateforme_client:
            pattern:    ^/espace-client/
            anonymous: true
            provider:  client
            form_login:
                login_path: login-client
                check_path: login_check_client
            logout:
                path:   logout
                target: /
        

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
