<?php

namespace Ayigi\ClientBundle\Repository;

/**
 * PaiementDoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementDoneRepository extends \Doctrine\ORM\EntityRepository
{
	public function findClientPaiement($idclient)
	{
	  
	  $qb = $this->createQueryBuilder('p')
					->leftJoin('p.client', 'c')
    				->addSelect('c')      
	            	->where('c.id = :idclient')
	            	->setParameter('idclient', $idclient);
	 
			return $qb->getQuery()->getResult();
	}



}// fin class
